### ISSUE TITLE
Reducing the bundle size

### ISSUE THREAD

**Issue by cezarlz** [UYEONG/react-preloader-icon#12]
Hey, this library helps me a lot, but I was facing some issues related to its bundle size.

In my case, for instance, I've been using only the OVAL icon type but the final bundle is adding the other ones as well.

We can see the bundle analyzer here:

![image](https://user-images.githubusercontent.com/954889/36372342-0eaa6190-1565-11e8-8189-9cd073a91064.png)

As you can see, the lib has added the other icon types, unnecessarily.

Is there a way to don't add them? Maybe an approach like `lodash` and `date-fns` do?

```js
import PreloaderIconOval from 'react-preloader-icon/oval';
```

Thank you!

**Comment by UYEONG** [comment]
I released version 0.2.0!
You can use it like this.

```
import PreloaderIcon from 'react-preloader-icon';
import Oval from 'react-preloader-icon/loaders/Oval';

<PreloaderIcon
    loader={Oval}
    size={32}
    strokeWidth={8}
    strokeColor="#F0AD4E"
    duration={800}
/> 
```

<img width="561" alt="2018-03-30 1 48 26" src="https://user-images.githubusercontent.com/1321707/38102755-2eafd43e-33bf-11e8-90c6-bb8998e90d5a.png">

Thank you!
